# swagger
swagger:
  enabled: true
  title: swagger example
  description: api example
  version: 1.0
  contact:
    name: example
    email: example@outlook.com
  base-package: com.github.sunnus3.swagger.controller