apiVersion: v1
kind: Namespace
metadata:
  name: flink
---
apiVersion: v1
kind: Service
metadata:
  namespace: flink
  name: jobmanager
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
      name: ui
    - port: 6123
      targetPort: 6123
      name: tcp
  selector:
    app: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flink
  name: jobmanager
spec:
  selector:
    matchLabels:
      app: jobmanager
  template:
    metadata:
      labels:
        app: jobmanager
    spec:
      containers:
        - name: flink
          image: flink:scala_2.11
          args:
            - jobmanager
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: jobmanager
          ports:
            - containerPort: 6123
            - containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /home
              name: job
      volumes:
        - name: job
          hostPath:
            path: /home
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  namespace: flink
  name: taskmanager
spec:
  ports:
    - port: 6121
      targetPort: 6121
      name: tcp1
    - port: 6122
      targetPort: 6122
      name: tcp2
  selector:
    app: taskmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flink
  name: taskmanager
spec:
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: flink
          image: flink:scala_2.11
          args:
            - taskmanager
          ports:
            - containerPort: 6121
            - containerPort: 6122
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: jobmanager
      initContainers:
        - name: init-jobmanager
          image: busybox
          command: ['sh', '-c', 'until nslookup jobmanager; do echo waiting for jobmanager; sleep 2; done;']