spring:
  redis:
    database: 0 # 数据库索引 默认 0
    host: dell.com # 地址，默认 localhost
    port: 6379 # 端口，默认6379
    password: # 密码，默认为空
    jedis:
      pool:
        max-active: 8 # 最大链接数，默认8，使用负数表示没有限制
        max-idle: 8 # 最发空闲链接
        min-idle: 8 # 最小空闲链接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000 # 链接超时时间 ms