auto:
  dubbo:
    version: 1.0.0

spring:
  application:
    name: auto-dubbo-provider
dubbo:
  scan:
    base-packages: com.github.sunnus3.example.dubbo.service
  protocol:
    name: dubbo
    port: 25880
  registry:
    address: N/A

