spring:
  application:
    name: nacos-dubbo-provider

dubbo:
  protocol:
    name: dubbo
    port: 25880
  registry:
    address: nacos://dell.com:8848
  application:
    name: ${spring.application.name}
  scan:
    base-packages: com.github.sunnus3.example.dubbo.nacos

nacos:
  config:
    server-addr: dell.com:8848
  dubbo:
    version: 1.0.0