info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
server:
  port: 8080
management:
  server:
    port: 8099
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "*" # * 在 yml 属于关键字，所以需要加引号
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true