
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.108:9001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5 # 客户端每隔 n 秒向服务端发送数据包
    lease-renewal-interval-in-seconds: 15 # 客户端告知服务端：若在 n 秒内没有向服务端发送消息，则服务端将其从列表中删除
logging:
  level:
    com:
      netflix: DEBUG
spring:
  application:
    name: eureka-producer